[platformio]
src_dir = src

[env:leaf_3_2_6_msc_reference]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.10/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_mode = qio
board_upload.flash_size = 8MB
board_upload.maximum_size = 8388608

build_unflags = -D ARDUINO_USB_MODE
build_flags =
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D ARDUINO_USB_MSC_ON_BOOT=0
    -D ARDUINO_USB_DFU_ON_BOOT=0

monitor_speed = 115200
