[env:leaf_3_2_6_dev]
extends = env:_dev
build_flags = 
    ${env:_dev.build_flags}
    -Isrc/variants/leaf_3_2_6
    -D _DEBUG
monitor_filters = esp32_exception_decoder
monitor_speed = 115200

[env:leaf_3_2_6_release]
extends = env:_release
build_flags =
    ${env:_release.build_flags}
    -Isrc/variants/leaf_3_2_6

[env:leaf_3_2_6_recorder]
extends = env:_release
lib_deps =
    robtillaart/TCA9555@0.4.1
build_flags =
    ${env:_release.build_flags}
    -Isrc/variants/leaf_3_2_6
    -D LEAF_RAW_RECORDER
build_src_filter =
    -<*>
    +<raw_logger/*.cpp>
    +<hardware/io_pins.cpp>
    +<system/version_info.cpp>
